import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import LayoutClient from "./layout-client";

const inter = localFont({
  src: '../public/fonts/Inter-4.0/web/InterVariable.woff2',
  variable: '--font-inter',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} scroll-smooth`}>
      <body
        className={`relative bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900`}
      >
        <LayoutClient>
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
